# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, help_text='Leave blank to auto-calculate based on the duration.')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('registration_number', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'car classes',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('make', models.CharField(choices=[('alfaromeo', 'Alfa Romeo'), ('audi', 'Audi'), ('bentley', 'Bentley'), ('bmw', 'BMW'), ('buick', 'Buick'), ('byd', 'BYD'), ('cadillac', 'Cadillac'), ('caterham', 'Caterham'), ('chevrolet', 'Chevrolet'), ('chrysler', 'Chrysler'), ('citroen', 'Citroen'), ('dacia', 'Dacia'), ('daewoo', 'Daewoo'), ('daihatsu', 'Daihatsu'), ('dodge', 'Dodge'), ('fiat', 'Fiat'), ('ford', 'Ford'), ('fso', 'FSO'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('infinity', 'Infinity'), ('iveco', 'Iveco'), ('jaguar', 'Jaguar'), ('jeep', 'Jeep'), ('kia', 'Kia'), ('lada', 'Lada'), ('lancia', 'Lancia'), ('landrover', 'Land Rover'), ('lexus', 'Lexus'), ('mazda', 'Mazda'), ('mercedesbenz', 'Mercedes-Benz'), ('mia', 'Mia'), ('mini', 'Mini'), ('mitsubishi', 'Mitsubishi'), ('nissan', 'Nissan'), ('opel', 'Opel'), ('peugeot', 'Peugeot'), ('porsche', 'Porsche'), ('qoros', 'Qoros'), ('renault', 'Renault'), ('saab', 'Saab'), ('seat', 'SEAT'), ('skoda', 'Skoda'), ('smart', 'Smart'), ('ssangyong', 'Ssangyong'), ('subaru', 'Subaru'), ('suzuki', 'Suzuki'), ('tata', 'Tata'), ('tesla', 'Tesla'), ('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('volvo', 'Volvo')], default='byd', max_length=12)),
                ('name', models.CharField(default='E6', max_length=20)),
                ('year', models.PositiveIntegerField(default=2018)),
                ('engine', models.CharField(choices=[('cng', 'CNG'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('gasoline', 'Gasoline'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='electric', max_length=8, verbose_name='engine / fuel type')),
                ('current_type', models.CharField(blank=True, choices=[('ac', 'AC'), ('dc', 'DC')], max_length=2, null=True)),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to='bookings.CarClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('keycore_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_put_back', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('latest_operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('pickup', 'Pick up'), ('putback', 'Put back')], editable=False, max_length=7)),
                ('latest_status', models.CharField(choices=[('cancelled', 'Cancelled'), ('ended', 'Ended'), ('valid', 'Valid')], editable=False, max_length=9)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='bookings.Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='driver')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='KeyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('pickup', 'Pick up'), ('putback', 'Put back')], max_length=7)),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('ended', 'Ended'), ('valid', 'Valid')], max_length=9)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.Key')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, verbose_name='Town / City')),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='bookings.Location', verbose_name='current location'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='bookings.CarModel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(blank=True, help_text='You must specify either a car class or a specific car', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_ending', to='bookings.Location', verbose_name='Drop-off location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_starting', to='bookings.Location', verbose_name='Pick up location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='driver'),
        ),
    ]
