# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surecam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSummary',
            fields=[
            ],
            options={
                'verbose_name': 'event summary',
                'verbose_name_plural': 'event summaries',
                'proxy': True,
                'indexes': [],
            },
            bases=('surecam.event',),
        ),
        migrations.CreateModel(
            name='TripSummary',
            fields=[
            ],
            options={
                'verbose_name': 'trip summary',
                'verbose_name_plural': 'trip summaries',
                'proxy': True,
                'indexes': [],
            },
            bases=('surecam.trip',),
        ),
    ]
